### ISSUE TITLE
Shards Issue : install does not work

### ISSUE THREAD

**Issue by iambudi** [crystal-lang/crystal-mysql#81]
```
Crystal 0.30.0 (2019-08-01)

LLVM: 8.0.0
Default target: x86_64-apple-macosx
```
```yaml
dependencies:
  db:
    github: crystal-lang/crystal-db
  sqlite3:
    github: crystal-lang/crystal-sqlite3  
  mysql:
    github: crystal-lang/crystal-mysql   
```
```
Fetching https://github.com/crystal-lang/crystal-mysql.git
git fetch --all --quiet
git tag --list --column=never
versions: 0.7.0, 0.6.0, 0.5.1, 0.5.0, 0.4.0, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.1.0
git ls-tree -r --full-tree --name-only v0.7.0 -- shard.yml
git show v0.7.0:shard.yml
git ls-tree -r --full-tree --name-only v0.7.0 -- shard.yml
git show v0.7.0:shard.yml
git ls-tree -r --full-tree --name-only v0.6.0 -- shard.yml
git show v0.6.0:shard.yml
**Error resolving db (*, ~> 0.6.0, ~> 0.5.0)**
```

**Comment by RX14** [comment]
There are conflicting version requirements among the dependencies, one requires `crystal-db` `~> 0.6.0`, and one requires `~> 0.5.0`. THis is probably fixed by new crystal-sqlite3 and crystal-mysql updates

**Comment by iambudi** [comment]
**Error resolving db (~> 0.7.0, ~> 0.6.0). Still conflict.

**Comment by bcardiff** [comment]
Tomorrow i will release a crystal-sqlite3 with db ~> 0.7.0 as dependency

**Comment by joshmn** [comment]
Also getting `Error resolving db (*, ~> 0.6.0, ~> 0.6.0, ~> 0.6.0, *, ~> 0.6.0, ~> 0.7.0)` for a default amber install.

**Comment by ashishbista** [comment]
I'm using `crystal-pg`, not sqlite3. I'm still getting the same issue.

```
Fetching https://github.com/will/crystal-pg.git
git fetch --all --quiet
git tag --list --column=never
versions: 0.9.1, 0.9.0, 0.8.0, 0.7.1, 0.7.0, 0.6.1, 0.6.0, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.19.0, 0.18.1, 0.18.0, 0.17.0, 0.16.1, 0.16.0, 0.15.0, 0.14.1, 0.14.0, 0.13.4, 0.13.3, 0.13.2, 0.13.1, 0.13.0, 0.12.0, 0.11.0, 0.10.0, 0.1.0
git ls-tree -r --full-tree --name-only v0.19.0 -- shard.yml
git show v0.19.0:shard.yml
git ls-tree -r --full-tree --name-only v0.18.1 -- shard.yml
git show v0.18.1:shard.yml
git ls-tree -r --full-tree --name-only v0.7.0 -- shard.yml
git show v0.7.0:shard.yml
Error resolving db (~> 0.7.0, ~> 0.6.0)
```

**Comment by iambudi** [comment]
```yaml
dependencies:
mysql:
    github: crystal-lang/crystal-mysql
  sqlite3:
    github: crystal-lang/crystal-sqlite3  
```

Now it works nicely. Thanks.
